### ISSUE TITLE
Sending email error

### ISSUE THREAD

**Issue by guilhermedjr** [0G4briel/ReachUp#13]
System.ArgumentNullException: Value cannot be null. (Parameter 'text')
   at MimeKit.MailboxAddress.Parse(ParserOptions options, String text)
   at MimeKit.MailboxAddress.Parse(String text)
   at ReachUp.EmailSender.CreateEmailMessage(Message message) in 
  LibraryClasses\Classes\EmailSender.cs:line 39

` private MimeMessage CreateEmailMessage(Message message)
  {
          var emailMessage = new MimeMessage();
          emailMessage.From.Add(
             MailboxAddress.Parse(_emailConfig.From)
             );
         emailMessage.To.Add(message.To);
         emailMessage.Subject = message.Subject;
         emailMessage.Body = 
           new TextPart(
             MimeKit.Text.TextFormat.Text
         ) {Text = message.Content};

         return emailMessage;
    }`

**Comment by guilhermedjr** [comment]
The problem was in reading the json.  when the email sending actions were on the WebAPI, they worked because appsettings.json (which had the information for authentication and access to the email server that are now in a static class) is in the same directory.  for it to work, now that everything is in the LibraryClasses, the static information must also be in the same directory.  you can't read an appsettings.json file here (most likely because there is no such thing as a Startup.cs class), so the need for a static class.
